name: 'Michael Gill '
favicon: null
layout_spectrum: 0.15088585810735822
typography_spectrum: 0.6033343775197864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12684314488433301
  lightness: 0.9299042085185647
  saturation: 0.15214430168271065
  rhythmicContrast: 0.1620278067421168
purpose: []
